### ISSUE TITLE
Optimize install applications

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/role_python#1]
refert to role_node, optimize install applications:

1. install app on demand
2. default apps:  Django, TensorFlow (and its GUI tool tensowboard), ansible
3. fix ansible-python(all apps be selected), ansible-tensorfolw, anisble-ansible
4. intall `virtualenvwrapper` in the file main.yml

**Comment by qiaofeng1227** [comment]
refer to: https://github.com/websoft9dev/role_python_apps/blob/master/tasks/django.yml and add DJango application

**Comment by qiaofeng1227** [comment]
Is [tensorboard](https://www.tensorflow.org/tensorboard?hl=zh-cn) installed by default? how to access it?

**Comment by zengxc-1996** [comment]
`cat /data/wwwroot/django/django_project/django_project/wsgi.py`
```
"""
WSGI config for django_project project.

It exposes the WSGI callable as a module-level variable named ``application``.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/howto/deployment/wsgi/
"""

import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'django_project.settings')

application = get_wsgi_application()
```

**Comment by chendelin1982** [comment]
Suggest install pyinstaller: https://pyinstaller.readthedocs.io/en/stable/

**Comment by qiaofeng1227** [comment]
Done
